# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPUXk1YPpMNLOlIOnp82UtKSWGOL1QFx
"""

for i in range(1, 5 + 1):
    for j in range(1, i + 1):
        if j == 1 or i == 5 or i == j:
            print(j, end=" ")
        else:
            print(" ", end=" ")
    print( )

for i in range(6,0,-1):
    for j in range(1,i+1):
        if j == 1 or j==i or i == 6:
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()

for i in range(1,8):
     print("*" *i)

for i in range(6,0,-1):
  for j in range (i):

     print("*",end='')
  print()

for i in range(1,6):
  for j in range(1,i+1):
      if j==1:
         print("*",end='')
      else:
        print(" ",end='')
  print()

for i in range(1, 5 + 1):
    for j in range(1, 5 + 1):
        if i == 1 or i == 5 or j == 1 or j == 5 :
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print( )

for i in range(1, 8+1 ):
    for j in range(8 - i):
        print(" ", end=" ")
    for k in range(1, i + 1):
        if k == 1 or k == i or i == 8:
            print("*", end=" ")
        else:
            print("_", end=" ")
    print()

for i in range(1, 5 + 1):
    for j in range(1, i + 1):
        if j == 1 or i == 5 or i == j:
            print(j, end=" ")
        else:
            print(j, end=" ")
    print( )



num = 1
for i in range(1, 5 + 1):
    for j in range(1, i + 1):
        print(num, end=" ")
        num += 1
    print()

a,b=0,1
for i in range(1,8):
  for j in range(i):
    print(a,end=" ")
    a,b=b,a+b
  print("")