# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4BPkrLd-kphFIdKn-sMYgIwK6jmR8Om
"""

data=[1,2,3,5]

n=data
while n>10:
    total=0
    while n>0:
         list_digit=n%10
         total=total+last_digit
         n//=10
    n=total
print(total)

data=[[1,2],[3,4],[5,6]]
new=[]
for i in data:
    for j in i:
        new.append(j)
print(new)

data=[[1,2],[3,4],[5,6]]
new=[]
for i in data:
     nested_list=i
     for j in nested_list:
        new.append(j)
print(new)

data=[[1,2],[3,4],[5,6]]
def flatten(data):
    new=[]
    for i in data:
        nested_list=i
        for j in nested_list:
            new.append(j)
    return new
print(flatten(data))

