# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWOPTSMuXXuep9ZKDr_9I2uBfpVzxj4E
"""

def display():
   print("hi")
   print("hello")
   print("byy")

display()

def add():
 a=10
 b=90
 sum=a+b
 print(sum)
add()

def add():
  a=30
  b=99
  sum=a+b
  print(sum)
add()

def add():
  a=int(input())
  b=int(input())
  sum=a+b
  print(sum)
add()

def f1(a,b):
  print(int(a)+int(b))

f1(10,45)
f1(90,10)

def f1(a,b):
  print(int(a)+int(b))
  return"hello"
'''
print(f1(10,45))
'''
print(f1(90,10))

def f1(a,b):
  print(int(a)+int(b))
  return"hello"

print(f1(10,45))

print(f1(90,10))

'''
parameter    return
yes           yes
no            yes
yes           no
no            no
'''

def sum():
  a=5+88
  return a
sum()

def sum(a,b):
  a+=b
  return a

sum(77,88)

def f1(a,b):
  print(int(a)+int(b))
  return"welcome"

print(f1(68,45))

print(f1(110,10))

def f1(a,b):
  return a+b

print(f1(34,68))

def f1(a,b=8,c=6):
  return a,b,c

print(f1(34))